services:
  db:
    image: postgres
    restart: always
    ports: "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${USERNAME}
      POSTGRES_DB: 'ny_taxi'
    volumes:
      - ny_taxi_postgres_data:/var/lib/postgresql/data 
 